ar_teleop_franka_controller:
    type: kth_franka_controllers/ARTeleopFrankaController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1 

kth_cartesian_velocity_effort_interface_controller:
    type: franka_example_controllers/KthCartesianVelocityEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_cartesian_pose_effort_interface_controller:
    type: franka_example_controllers/KthCartesianPoseEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_joint_pose_effort_interface_controller:
    type: franka_example_controllers/KthJointPoseEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_joint_velocity_effort_interface_controller:
    type: franka_example_controllers/KthJointVelocityEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

kth_joint_acceleration_effort_interface_controller:
    type: franka_example_controllers/KthJointAccelerationEffortInterfaceController    
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    Kp: 
        - 400 
        - 400 
        - 400 
        - 30 
        - 30 
        - 30 
    impedance: 1     
    static: 1    
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0


kth_dual_arm_centroid_pose_effort_interface_controller:
    type: franka_example_controllers/KthDualArmCentroidPoseEffortInterfaceController
    left:
        arm_id: panda_left
        joint_names:
            - panda_left_joint1
            - panda_left_joint2
            - panda_left_joint3
            - panda_left_joint4
            - panda_left_joint5
            - panda_left_joint6
            - panda_left_joint7
        Kp: 
            - 400 
            - 400 
            - 400 
            - 30 
            - 30 
            - 30 
        impedance: 1     
        static: 1
    right:
        arm_id: panda_right
        joint_names:
            - panda_right_joint1
            - panda_right_joint2
            - panda_right_joint3
            - panda_right_joint4
            - panda_right_joint5
            - panda_right_joint6
            - panda_right_joint7
        Kp: 
            - 400 
            - 400 
            - 400 
            - 30 
            - 30 
            - 30 
        impedance: 1     
        static: 1
    Kpos: 250.0
    Kor: 150.0
    Mdpos: 1.0
    Mdor: 1.0

